import { StyleSheet, Platform } from 'react-native';

export default function getLandingStyles(width: number) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    scrollContent: {
      paddingBottom: 40,
    },
    hero: {
      paddingHorizontal: 24,
      paddingTop: 80,
      paddingBottom: 60,
      flexDirection: Platform.OS === 'web' && width > 800 ? 'row' : 'column',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#f8fafc',
    },
    heroTextContent: {
      flex: 1,
      maxWidth: Platform.OS === 'web' && width > 800 ? '50%' : '100%',
      marginBottom: 40,
    },
    badge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fef3c7',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      alignSelf: 'flex-start',
      marginBottom: 20,
      gap: 8,
    },
    badgeText: {
      color: '#92400e',
      fontWeight: '700',
      fontSize: 12,
    },
    title: {
      fontSize: Platform.OS === 'web' && width > 800 ? 56 : 40,
      fontWeight: '900',
      color: '#0f172a',
      lineHeight: Platform.OS === 'web' && width > 800 ? 64 : 48,
      marginBottom: 20,
    },
    highlight: {
      color: '#6366f1',
    },
    subtitle: {
      fontSize: 18,
      color: '#64748b',
      lineHeight: 28,
      marginBottom: 40,
    },
    buttonGroup: {
      flexDirection: Platform.OS === 'web' && width > 500 ? 'row' : 'column',
      gap: 16,
    },
    primaryButton: {
      flexDirection: 'row',
      backgroundColor: '#6366f1',
      paddingHorizontal: 32,
      paddingVertical: 18,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#6366f1',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 8,
    },
    primaryButtonText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '700',
    },
    secondaryButton: {
      flexDirection: 'row',
      backgroundColor: '#fff',
      paddingHorizontal: 32,
      paddingVertical: 18,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: '#e2e8f0',
    },
    secondaryButtonText: {
      color: '#4f46e5',
      fontSize: 18,
      fontWeight: '700',
    },
    previewContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    phoneFrame: {
      width: 280,
      height: 560,
      backgroundColor: '#1e293b',
      borderRadius: 40,
      padding: 12,
      borderWidth: 8,
      borderColor: '#334155',
    },
    phoneScreen: {
      flex: 1,
      backgroundColor: '#fff',
      borderRadius: 24,
      padding: 16,
    },
    mockHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 24,
      gap: 12,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#e2e8f0',
    },
    mockTextShort: {
      width: 100,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#e2e8f0',
    },
    mockCard: {
      width: '100%',
      height: 80,
      borderRadius: 16,
      backgroundColor: '#f1f5f9',
      marginBottom: 16,
    },
    featuresSection: {
      paddingHorizontal: 24,
      paddingVertical: 80,
      alignItems: 'center',
    },
    sectionTitle: {
      fontSize: 32,
      fontWeight: '800',
      color: '#0f172a',
      marginBottom: 48,
      textAlign: 'center',
    },
    featuresGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 24,
      maxWidth: 1200,
    },
    featureCard: {
      width: Platform.OS === 'web' && width > 600 ? 280 : '100%',
      backgroundColor: '#fff',
      padding: 32,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: '#f1f5f9',
      alignItems: 'flex-start',
    },
    iconContainer: {
      width: 64,
      height: 64,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 24,
    },
    featureTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#1e293b',
      marginBottom: 12,
    },
    featureDescription: {
      fontSize: 16,
      color: '#64748b',
      lineHeight: 24,
    },
    ctaSection: {
      paddingHorizontal: 24,
      paddingVertical: 60,
    },
    ctaCard: {
      backgroundColor: '#6366f1',
      padding: 48,
      borderRadius: 40,
      alignItems: 'center',
      maxWidth: 1000,
      alignSelf: 'center',
      width: '100%',
    },
    ctaTitle: {
      fontSize: 32,
      fontWeight: '800',
      color: '#fff',
      marginBottom: 16,
      textAlign: 'center',
    },
    ctaSubtitle: {
      fontSize: 18,
      color: '#e0e7ff',
      marginBottom: 32,
      textAlign: 'center',
    },
    ctaButton: {
      flexDirection: 'row',
      backgroundColor: '#fff',
      paddingHorizontal: 32,
      paddingVertical: 18,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ctaButtonText: {
      color: '#6366f1',
      fontSize: 18,
      fontWeight: '700',
    },
    footer: {
      paddingVertical: 40,
      borderTopWidth: 1,
      borderTopColor: '#f1f5f9',
      alignItems: 'center',
    },
    footerText: {
      color: '#94a3b8',
      fontSize: 14,
    },
  });
}
